/*********************************************************
*	Chartlet Script Document generated by Chartlet.dll
*	Used for dynamic tooltip display
*	Please view http://www.chartlet.cn for more information
*	FanG Corp. 2009
*********************************************************/
/* The global variables below can be used by any other js function you defined*/ 
var left,width,top,height,value;
/* The function is for value show in Tooltip*/
 function showTips(args){
var img=event.srcElement;
var ox=event.offsetX;
var oy=event.offsetY;
var argsGroup=args.split("|");
left=argsGroup[0].split(",");
width=argsGroup[1].split(",");
top=argsGroup[2].split(",");
height=argsGroup[3].split(",");
value=argsGroup[4].split(",");
var nowAlt=img.longDesc;
for(i=0;i<left.length;i++){
if(ox>parseInt(left[i]) && ox<parseInt(left[i])+parseInt(width[i])){
if(oy>parseInt(top[i]) && oy<parseInt(top[i])+parseInt(height[i])){
nowAlt=	value[i];
break;
}}}
img.alt=nowAlt;
}
